version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/run:
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          build: npm run lint && npm run lint:cypress
          # runs Cypress tests by default
          post-steps:
            - run:
                name: Jest tests
                command: npm test
